# Name of site
name: Daniel Osborne
description: Software Engineer & Rambler
url: https://dkoz.me

# URL of avatar
avatar: https://avatars.githubusercontent.com/u/11066541?v=4

#
# Social Media links
#

# Social Media/Contact links
footer-links:
  email: daniel@dkoz.me
  github: mrdkoz
  linkedin: dkosborne
  twitter: mrdkoz

# Project Repository URL (http://username.github.io/repository-name)
baseurl: ""

permalink: /:categories/:year/:month/:title

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
